export const SubdomainMap: Record<string, string> = {
  localhost: "default",
  "127.0.0.1": "default",
  dev: "default",
  stg: "default",
  app: "default",
  angloamerican: "angloamerican",
  stg1: "angloamerican",
  networkrail: "networkrail",
  stgnr: "networkrail",
  tfl: "tfl",
  stgtfl: "tfl",
  stgtfl1: "tfl",
  devtfl: "tfl",
  stgvwfs: "vwfs",
  vwfs: "vwfs",
  stgquench: "quench",
  quench: "quench",
};
